# Generated by Django 4.2 on 2025-03-14 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelrequest_app', '0005_rename_name_admin_username_remove_admin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
