# Generated by Django 4.2 on 2025-03-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelrequest_app', '0006_alter_travelrequest_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
