# Generated by Django 4.2 on 2025-03-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelrequest_app', '0007_travelrequest_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='is_closed',
        ),
    ]
